version: '2.4'
services:

    # ---------------------------------
    # TRAEFIK
    # ---------------------------------
    traefik:
        image: traefik:2.4
        volumes:
          - ./traefik/traefik.yml:/etc/traefik/traefik.yml
          - /var/run/docker.sock:/var/run/docker.sock
        links:
          - server
        ports:
         - "3000:80"
         - "127.0.0.1:8080:8080"

    # ---------------------------------
    # DB
    # ---------------------------------
    maria-db:
      container_name: maria-db
      image: mariadb:10.5.9
      hostname: maria-db
      command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_TABLE}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
      volumes:
        - vol-db-data:/var/lib/mysql
      ports:
        - '127.0.0.1:3306:3306'
      labels:
        - traefik.enable=false
      healthcheck:
        test: "/usr/bin/mysql --user=${DB_USER} --password=${DB_PASS} --execute \"SHOW DATABASES;\""
        interval: 3s
        timeout: 1s
        retries: 5
      

    # ---------------------------------
    # SERVER
    # ---------------------------------
    server:
      hostname: server
      build: .
      restart: always
      links:
        - maria-db
      labels:
        - "traefik.http.routers.${NAME}.rule=PathPrefix(`/`)"
        - traefik.http.services.${NAME}.loadBalancer.sticky.cookie.name=server_id
        - traefik.http.services.${NAME}.loadBalancer.sticky.cookie.httpOnly=true
      volumes:
        - vol-server-data:/usr/src/app/static
      depends_on:
        maria-db:
          condition: service_healthy

volumes:
  vol-db-data:
    driver: local
  vol-server-data:
    driver: local