export default {
    API_BASE_PATH: "/api/json/v1/",
    LOCALSTORAGE: import.meta.env.MODE.PARAMS.localstorage || false,
    DBNAME: "server_software_db_" + ( import.meta.env.MODE.NAME || '').replace(/[^\w-]/gi, ''),
    APP_NAME: import.meta.env.MODE.NAME || "epyo",
    APP_HISTORY: import.meta.env.MODE.PARAMS.history || false,
    APP_ROLES: import.meta.env.MODE.PARAMS.roles || ["operator", "operator_1", "operator_2", "manager", "supervisor", "dsi"],
    APP_AUTO_LOGIN: import.meta.env.MODE.PARAMS.auto_login || false,
    APP_USERNAME: import.meta.env.MODE.PARAMS.username || null,
    APP_PASSWORD: import.meta.env.MODE.PARAMS.password || null,
    APP_STEPS: import.meta.env.MODE.PARAMS.steps || false,
    APP_BROKER_CONNECT: import.meta.env.MODE.PARAMS.broker || false,
    APP_BROKER_TOPIC: import.meta.env.MODE.PARAMS.broker_topic || ['mailer/%u/#', 'pictures/%u/#'],
    APP_BROKER_STORE_MESSAGES: import.meta.env.MODE.PARAMS.broker_store_messages || false,
    APP_SCANLESS: import.meta.env.MODE.PARAMS.scanless || false,
    APP_SCANLESS_PORT: import.meta.env.MODE.PARAMS.scanless_port || '8383',
    APP_SCANLESS_PROTOCOL: import.meta.env.MODE.PARAMS.scanless_protocol || 'http',
    APP_SCANLESS_STORE_MESSAGES: import.meta.env.MODE.PARAMS.scanless_store_messages || false,
    APP_SCANLESS_TOPIC: import.meta.env.MODE.PARAMS.scanless_topic || ['fenceevent'],
    DEV: import.meta.env.DEV || false,
    VERSION: import.meta.env.MODE.VERSION || ''
};